<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Andrew22andrewhotmail.com</name>
   <tag></tag>
   <elementGuidId>dc64e138-be0b-4493-a7ee-f4184cef51ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f6f3e47-4bba-4f76-9e1d-6638ea730b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Usercontactsbox</value>
      <webElementGuid>fd7808c2-f10f-4821-b481-ebc947bca577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andrew22andrew@hotmail.com</value>
      <webElementGuid>a00300b1-88d5-4b08-9423-3f659fc168be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;Chatting&quot;]/div[@class=&quot;BigMessageContainer&quot;]/div[@class=&quot;MessageContainer&quot;]/div[@class=&quot;MessageCleft&quot;]/div[@class=&quot;Containerusercontactsbox&quot;]/div[@class=&quot;Usercontactsbox&quot;]</value>
      <webElementGuid>ecc4e9d8-e6e1-406e-b0e8-7177bf7c7ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/div[2]/div[2]</value>
      <webElementGuid>918932b0-6c83-40e0-9a0d-0c1ca7e512a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[4]</value>
      <webElementGuid>2c4c5686-42e2-46f4-948e-f92bd9101a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[10]</value>
      <webElementGuid>0f5c187e-089c-40f6-8bba-68d11cb613cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mohammedmsg Chat'])[1]/preceding::div[2]</value>
      <webElementGuid>10c374c9-6f86-499d-b169-858240c23444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hellokhaledmsg'])[1]/preceding::div[3]</value>
      <webElementGuid>aee27ce9-c062-4aaf-a7c2-fd61e3f650ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]</value>
      <webElementGuid>0299b698-19c4-4f20-8cec-24f03097d275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Andrew22andrew@hotmail.com' or . = 'Andrew22andrew@hotmail.com')]</value>
      <webElementGuid>31bd5324-3d80-4e22-957e-49fe480dd90a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
