<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_khaledmsgkhaledmsghotmail.com</name>
   <tag></tag>
   <elementGuidId>ed5c2b50-ba49-4a06-bc14-0aa2a9a57617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Usercontactsbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e60463a7-26d5-419a-9050-fbe0e3e0767a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Usercontactsbox</value>
      <webElementGuid>5df95f01-82a0-459d-950b-112d90509012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>khaledmsgkhaledmsg@hotmail.com</value>
      <webElementGuid>fe21e5f6-0695-4dbd-b154-72acd2fe9398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;Chatting&quot;]/div[@class=&quot;BigMessageContainer&quot;]/div[@class=&quot;MessageContainer&quot;]/div[@class=&quot;MessageCleft&quot;]/div[@class=&quot;Containerusercontactsbox&quot;]/div[@class=&quot;Usercontactsbox&quot;]</value>
      <webElementGuid>9e06651e-7688-4026-81cd-0dc0ba6af259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>a70e55c3-f1db-4a7c-becd-81a4098c2817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[2]</value>
      <webElementGuid>a4e6aeaa-1d7f-484e-8207-fb3179cedeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[8]</value>
      <webElementGuid>2f5ef6c7-6c81-4977-80fb-7b2d598e08dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mohammedmsg Chat'])[1]/preceding::div[4]</value>
      <webElementGuid>14891dce-4fbc-436b-a569-c745e397e1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>ea726dfa-3ee0-4e25-bb81-35483c83cf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'khaledmsgkhaledmsg@hotmail.com' or . = 'khaledmsgkhaledmsg@hotmail.com')]</value>
      <webElementGuid>7eaa6f3a-4d13-4470-bd96-df89ce9f80b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mohammedmsg Chat'])[1]/preceding::div[2]</value>
      <webElementGuid>13c5ec7e-7857-4249-8f49-f6cacede85e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
