<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>496d8c64-7803-4341-92e3-7e91eab6adf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9216fc47-894c-4876-87aa-5c712e2a1537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/dbjv7n54i/image/upload/v1734348310/Userimages/piir1elqm1qpqw0xa5eg.jpg</value>
      <webElementGuid>b490f1b3-8aff-457c-9205-bcdf421aa524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;navbar&quot;]/div[@class=&quot;Usericonnav&quot;]/img[1]</value>
      <webElementGuid>94d94d62-062b-4bc8-afb0-b9975afae159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div/div[2]/img</value>
      <webElementGuid>d87363c7-7ba8-49d0-bc55-1e086dcfb242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>588321a6-7930-47a8-9779-ef89e4f67f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734348310/Userimages/piir1elqm1qpqw0xa5eg.jpg')]</value>
      <webElementGuid>a36ac122-8b4d-450d-8dc2-cd276c081670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734348310/Userimages/piir1elqm1qpqw0xa5eg.jpg']</value>
      <webElementGuid>971bdeab-cbc2-48c2-9825-8d506c00977c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289721/Userimages/bieswi5txlbwpf5bw4ge.jpg')]</value>
      <webElementGuid>fe230427-cbca-40a0-ba1a-c9ac5df38fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289721/Userimages/bieswi5txlbwpf5bw4ge.jpg']</value>
      <webElementGuid>8effd07b-da61-4de6-9a5a-2a5dba836906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289596/Userimages/dpafqopcwuucor3ctood.jpg')]</value>
      <webElementGuid>9fb1e7c5-3020-4639-856a-34b4b8c9bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289596/Userimages/dpafqopcwuucor3ctood.jpg']</value>
      <webElementGuid>df4be0ed-2104-416d-9c50-94801106601a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1715199215/Userimages/pstavytcf9sbdxlnrxzt.jpg')]</value>
      <webElementGuid>bd4e8722-e1db-4745-8e70-65d7e1279d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1715199215/Userimages/pstavytcf9sbdxlnrxzt.jpg']</value>
      <webElementGuid>d4c98fe6-baea-43ee-81a4-d61ae65a2b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
