<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signup_signup_email</name>
   <tag></tag>
   <elementGuidId>b900c2d4-49c1-4eb5-a82d-1d5ac7bdcf92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cf6c79a-ddda-47cc-b48a-f066df7b2ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_email</value>
      <webElementGuid>bebe7365-6029-489f-8726-13a7c4187430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ac7deb39-5eaa-48ba-9b0b-9a532b134eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5c2cfe99-5e32-4547-ab33-82c9752c8b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_email&quot;)</value>
      <webElementGuid>306a32d0-fb07-4f41-a792-759661e90690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_email']</value>
      <webElementGuid>9cbd0043-a4da-4554-a473-c28b66303e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/form/div[2]/input</value>
      <webElementGuid>73dd17af-ce73-47e9-a258-fad18970eb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>01deead4-8143-422f-b607-33ace8fc1e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signup_email' and @type = 'email' and @placeholder = 'email']</value>
      <webElementGuid>27e0f3e7-ae42-4aec-be4b-2205fb6447c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
