<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signup_signup_username</name>
   <tag></tag>
   <elementGuidId>54e4e653-4b88-4823-9938-9f8de4419ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e43ddfd2-700b-4204-9112-b0f95aa9e86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_username</value>
      <webElementGuid>b7e08ee6-2ea9-4b45-bb65-dacdb2e54235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c53abe82-53a7-48f1-aa7b-1610c7b17386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>6d2ca043-81bd-4451-9d21-b7152a998158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_username&quot;)</value>
      <webElementGuid>48685baf-9f05-4f56-8eb2-f8b5c5a026a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_username']</value>
      <webElementGuid>d1cb6264-fecb-49fb-815e-c854868b1bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div/form/div/input</value>
      <webElementGuid>7eaeca81-21b9-43ce-a052-047cc4f6938b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c0693de0-557b-420a-8ef0-bd1ef12d433e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signup_username' and @type = 'text' and @placeholder = 'username']</value>
      <webElementGuid>42ee4d17-e13c-4d9d-89d5-f4f9aa30e6ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
