<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_SendMessage</name>
   <tag></tag>
   <elementGuidId>22276c55-7d61-46fd-a4b7-7891b4b0a2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div[3]/div/div/div[2]/div[2]/div[3]/button/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.CustomButton > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>23825406-5fef-45b3-8e2b-eb27b3ad1c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SendMessage</value>
      <webElementGuid>55cfb767-17a1-4ff1-9de5-7d7fdfe95626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;ListingInfo&quot;]/div[@class=&quot;Details-wrapper&quot;]/div[@class=&quot;Details-Container&quot;]/div[@class=&quot;ListingRight&quot;]/div[@class=&quot;Listing-content&quot;]/div[@class=&quot;purchase-info&quot;]/button[@class=&quot;CustomButton&quot;]/p[1]</value>
      <webElementGuid>a105c187-b863-45e9-a24d-b73273d2b817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div[2]/div[2]/div[3]/button/p</value>
      <webElementGuid>4bb56d16-3fcf-4770-96a3-19587d949b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NileDrive'])[2]/preceding::p[2]</value>
      <webElementGuid>e45fe10e-4677-492c-830a-bf0164abeb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Products'])[1]/preceding::p[3]</value>
      <webElementGuid>4fc8d875-2ef2-4bf4-a285-2f313c607987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SendMessage']/parent::*</value>
      <webElementGuid>fe8ab4c4-89d7-4ec5-9b8b-464946e90a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>4d7b12b3-1baa-4fd6-9897-93698eb5c4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'SendMessage' or . = 'SendMessage')]</value>
      <webElementGuid>442095d1-c98d-427a-ba82-08f702c8e35c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
