<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Car TypeSUVSedanSport</name>
   <tag></tag>
   <elementGuidId>c4a01ff3-e49d-4c96-a001-356a02f906aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='carType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#carType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d63b1238-e786-4a52-9af6-43f0c404617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carType</value>
      <webElementGuid>1f5d5ab7-3b0c-4d22-a0ce-2de6350e395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carType</value>
      <webElementGuid>696aae4a-8d4b-4014-a38d-a30cda53f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Car TypeSUVSedanSport</value>
      <webElementGuid>3fb5fc1f-12c4-4e33-9ad3-7387f67625ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carType&quot;)</value>
      <webElementGuid>66161422-492e-4e07-bb9e-d0094bc5b284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='carType']</value>
      <webElementGuid>925cac3e-935c-4eac-877b-8598de888e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/form/div[5]/select</value>
      <webElementGuid>3d1294e2-e3ce-4b87-815d-d8f35fb28008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Name'])[1]/following::select[1]</value>
      <webElementGuid>54b59ca0-e4e2-4111-976d-7a3bb8b630d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Image'])[2]/following::select[1]</value>
      <webElementGuid>f91b2357-8968-412b-aeb1-af4d71302027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/preceding::select[1]</value>
      <webElementGuid>3b370c07-7e68-44fe-afdb-ed2ac9c6aba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Doors'])[1]/preceding::select[1]</value>
      <webElementGuid>f8999c7e-fcaf-47a6-9826-b1da51992a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>509ccb01-dd52-47db-b51f-ad82280deeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'carType' and @name = 'carType' and (text() = 'Select Car TypeSUVSedanSport' or . = 'Select Car TypeSUVSedanSport')]</value>
      <webElementGuid>3edeaa6b-6c81-4c5c-b414-882bddfb8c3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
